[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = __WIREGUARD_PRIVATE_KEY__
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH-FREE#12
PublicKey = MD0ct1eK6uHm/E0XJmTnjRG4idxzrffswFxGvwM6uWY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 135.136.39.66:51820

PersistentKeepalive = 25
